/** Declaration file generated by dts-gen */

declare namespace validate {
    function body(schema: any): any;

    function headers(schema: any): any;

    function params(schema: any, name: any): any;

    function query(schema: any): any;

    function validate(schema: any): any;

}


export = validate;