/** Declaration file generated by dts-gen */

declare class Elasticsearch {
    constructor(...args: any[]);

    count(...args: any[]): void;

    deleteById(...args: any[]): void;

    find(...args: any[]): void;

    initialize(...args: any[]): void;

    insert(...args: any[]): void;

    updateById(...args: any[]): void;

}

export = Elasticsearch;