/** Declaration file generated by dts-gen */

declare class Mysql {
    constructor(...args: any[]);

    deleteById(...args: any[]): void;

    find(...args: any[]): void;

    findById(...args: any[]): void;

    initialize(...args: any[]): void;

    insert(...args: any[]): void;

    insertMany(...args: any[]): void;

    startTransaction(...args: any[]): void;

    update(...args: any[]): void;

    updateById(...args: any[]): void;

}



export = Mysql;
