/** Declaration file generated by dts-gen */

declare class BaseModel {
    constructor(...args: any[]);

    setDataSouce(...args: any[]): void;

    setPrimaryKey(...args: any[]): void;

    setTable(...args: any[]): void;

}


export = BaseModel;